project:
  type: website
  output-dir: docs

website:
  title: "Safetots"
  navbar:
    left:
      - href: Rights of the Child 10Rs.qmd
        text: Rights
      - href: Competence 5Ws.qmd
        text: Competence
      - href: The 10Ns.qmd
        text: 10N
      - href: Crisis 10Cs.qmd
        text: Crisis
  sidebar:
   style: "floating"
   search: true
   contents:
    - The Safetots Mission and Story.qmd
    - Rights of the Child 10Rs.qmd
    - Competence 5Ws.qmd
    - The 10Ns.qmd
    - Crisis 10Cs.qmd
    - Research.qmd
    - Quality Improvement.qmd
    - Parental discussion.qmd
    - For Parents.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


