project:
  type: website

website:
  title: "Safetots"
  navbar:
    left:
      - href: Research.qmd
        text: research

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

