project:
  type: website
  output-dir: docs

website:
  title: "Safetots"
  navbar:
    left:
      - href: Rights of the Child 10Rs.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

