## Can Intubate -* Can't Oxygenate (10Cs)
This page is part of the Safetots Crisis SOPs, a framework for prevention and treatment of the most relevant crisis situations in pediatric anaesthesia.

### Summary
Persistent post-intubation hypoxia can rapidly lead to morbidity and even mortality. Early recognition and effective intervention using a structured approach is required.

### Background
* small children have short and narrow airways requiring small and fragile airway equipment
* obstruction and dislocation of airway devices are common during moving and positioning
* gastric distension significantly reduces functional residual capacity in small children and may considerably impair ventilation and gas exchange
* limited oxygenation and respiratory reserves in small children result in rapid development of hypoxemia, carbon dioxide accumulation and respiratory acidosis. High closing capacity in small children increases likelihood of pulmonary atelectasis leading to intra-pulmonary shunt and hypoxemia
* rapid administration of potent opioids may lead to thoracic rigidity
* pediatric patients are at higher risk for bronchial hyper-reactivity particularly those with respiratory infection, bronchopulmonary dysplasia or allergic diathesis
* congenital and acquired diseases may affect lower airway patency or can lead to an acute tracheal tube obstruction

### Prevention
* correct positioning of tracheal tube and safe, effective fixation of airway devices is paramount
* suitable and careful positioning and moving of patients with tracheal tube. Reassess proper position of airway devices after re-positioning.
* ensure stable position when oral procedures (ENT, cleft surgery, gastroenterology, cardiology (transesophageal echocardiography) are performed
* ensure adequate depth of anesthesia (+/* muscle paralysis)
* perform appropriate ventilation and recruitment strategies
* consider gastric decompression following airway manoeuvres
* children with copious secretions or pus are at risk of tracheal tube obstruction and patency requires regular checking and confirmation

### Treatment
* call for assistance, if in doubt -* take it out
* the acronym DOPES summarizes the most relevant immediately life-threatening causes and interventions that effectively treat the 'Can Intubate -* Can't Ventilate' situation
* Exclude and treat
* **D** -* Displacement of tracheal tube (endobronchial, esophageal and pharyngeal)
* **O** -* Obstruction of tracheal tube, respiratory valves or respiratory filter with secretion and functional airway obstructions (severe bronchospasm, opioids)
* **P** -* Pneumothorax
* **E** -* Equipment problems (disconnection, kinking of respiratory tubing)
* **S** -* Stomach & Specials (increased intra-abdominal pressure, pulmonary pathology, pulmonary-arterial hypertension, cardiac right-to-left shunts, alveolar collapse)

### Post Care
* debriefing is essential (patient, parent, staff)
* documentation (patient records, alert card, bracelet) if appropriate
* follow--up if and when required

### References
* Engelhardt T, Fiadjoe JE, Weiss M, Baker P, Bew S, Echeverry Marín P, von Ungern-Sternberg BS. A framework for the management of the pediatric airway. Paediatr Anaesth. 2019 Oct;29(10):985-992
* Weiss M, Engelhardt T. Proposal for the management of the unexpected difficult pediatric airway. Paediatr Anaesth 2010; 20: 454-64.
* Weiss M, Schmidt J, Eich Ch et al. Handlungsempfehlung zur Prävention und Behandlung des unerwartet schwierigen Atemwegs in der Kinderanästhesie. Anästh Intensivmed 2011; 52: S54-S63.
* Engelhardt T, Machotta A, Weiss M. Management strategies for the difficult paediatric airway. Trends in Anaesthesia and Critical Care 2013; 3: 183-7.
* Biarent D, Bingham R, Eich C, López-Herce J, Maconochie I, Rodríguez-Núñez A, Rajka T, Zideman D. European Resuscitation Council Guidelines for Resuscitation 2010Section 6. Paediatric life support. Resuscitation. 2010; 81: 1364-88.

