## Can´t Cannulate -* Failed Venous Access (10Cs)
This page is part of the Safetots Crisis SOPs, a framework for prevention and treatment of the most relevant crisis situations in pediatric anaesthesia.

### Summary
Intra-osseous access is the access of choice in life threatening emergencies

### Background
* venous access in children can be difficult resulting in multiple attempts and may fail
* delays in obtaining venous access can result in morbidity particularly during emergencies
* those most at risk are young children, the chronically ill, obese or premature infants
* intra-osseous access has no reported associated mortality in contrast to emergency central venous access

### Prevention
* careful clinical evaluation and preparation (patient, team, equipment and environment)
* maintain hydration (short fasting times)
* use topical anesthesia for awake cannulation

### Treatment
* use the vein you can see
* call for assistance
* failed conventional venous puncture may require alternative venous access techniques (ultrasound, vein light, vein viewer or others) and operator
* intra-osseous access is the access of choice in life threatening emergencies

### Post Care
* ensure secure taping of successful venous access
* consider establishing longterm central venous access (PICC, port, Broviac, Hickmann lines)

### References
* Nafiu OO, Burke C, Cowan A, Tutuo N, Maclean S, Tremper KK. Comparing peripheral venous access between obese and normal weight children. Paediatr Anaesth 2010; 20: 172-6.
* de Graaff JC, Cuper NJ, Mungra RA, Vlaardingerbroek K, Numan SC, Kalkman CJ. Near-infrared light to aid peripheral intravenous cannulation in children: a cluster randomised clinical trial of three devices. Anaesthesia 2013; 68:835-45.
* Triffterer L, Marhofer P, Willschke H, Machata AM, Reichel G, Benkoe T, Kettner SC. Ultrasound-guided cannulation of the great saphenous veinat the ankle in infants. Br J Anaesth. 2012;108: 290-4.
* Rothbart A, Yu P, Müller-Lobeck L, Spies CD, Wernecke KD, Nachtigall I. Peripheral intravenous cannulation with support of infrared laser vein viewing system in a pre-operation setting in pediatric patients. BMC Res Notes 2015; 8: 463.
* Weiss M, Gerber A. The substitute for the intravenous route. Anesthesiology 2001; 95: 1040-1.
* Schwartz D, Raghunathan K. Difficult venous access. Paediatr Anaesth 2009; 19: 60.
* Weiss M, Henze G, Eich C, Neuhaus D. Intraosseous infusion. An important technique also for paediatric anaesthesia. Anaesthesist 2009; 58: 863-75.
* Neuhaus D, Weiss M, Engelhardt T, Henze G, Giest J, Strauss J, Eich C. Semi-elective intraosseous infusion after failed intravenous access in pediatric anesthesia. Paediatr Anaesth 2010; 20: 168-71.
* Weiss M, Engelhardt T. Cannot cannulate: bonulate! Eur J Anaesthesiol 2012; 29: 257-8.
* Eich Ch, Weiss M, Neuhaus D et al. HE Handlungsempfehlung zur intraossären Infusion in der Kinderanästhesie. Anästh Intensivmed 2011; 52: S46-S52.




