## For Parents

img

### Frequently asked questions (FAQs)

### Does my child need a general anesthetic?
If a procedure or test is needed in a child, especially if it may cause distress or pain, or if it may take a long time, or needs the child to be very still, then anesthesia may be needed. Sometimes sedation is an alternative but often anesthesia is more reliable and as safe or safer. If no anesthesia was given for such tests or procedures the results would be bad and severe distress and harm could be caused.

### Is anesthesia for children safe?
Most anesthetics in children are short and are for small operations or procedures. These are usually safe in experienced hands and in well-organized departments that are used to caring for children.

### Why may some children get more problems with anesthesia? 
Smaller, younger and sicker children may have more problems with anesthesia because there is a smaller safety margin around normal and changes from normal can happen much more quickly. This is especially so in emergency or urgent cases.

Children who have complex surgery or longer procedures may also be more at risk of problems. The team needs a lot of training and experience to care for children to keep them safe during and after anesthesia and surgery.

### What sort of problems can occur and how common are they?
This table gives an idea of risks and how often they might occur.

  ----------------------------------------------------------------------- Risk    Risk level    Description   ------------------- ------------- ------------------------------------- Restlessness    1 in 10   Very common ("someone in your         family")
  Sickness    1 in 10   Very common 
  Dizziness   1 in 10   Very common
  Headache    1 in 100  Common ("someone in a street")
  Chest infection 1 in 1000 Uncommon ("someone in a village")
  Damage to teeth 1 in 1000 Uncommon
  Awareness   1 in 1000 Uncommon
  Serious allergy to  1 in 10 000   Rare ("someone in a small town")   drugs         
  Serious     1 in 10 000   Rare   complication of      local anesthesia      
  Serious     1 in 10 000   Rare   complication of      strong pain killers   
  Brain damage    \< 1 in 100   Very rare ("someone in a large town")       000   
  Death   \<\< 1 in 100 Very rare       000   
                    -----------------------------------------------------------------------
To put this in perspective, the risk of serious damage from an anesthetic is much less than the risk of travelling in a car.

### Is one anesthetic better than others?
At the moment there is no proof that one way of giving anesthesia is better than any other but your anesthesiologist will be able to advise on the preferred method for your child.

### Do anesthetic agents affect the intelligence and development of my child?
There is strong evidence in humans that a single, short, well-conducted anesthetic does not have effects on brain development. There is weak evidence that for long, or lots of anesthetics, some effects on behavior and learning in later life may be seen but this has to be balanced against the need for the procedure. Any effects of the anesthetic are around ten times less than other known factors.

Younger children have an increased risk of problems so could my child's operation be delayed until they are older?
The best age for a procedure should be discussed openly with your team as for some cases there are risks in delaying or postponing procedures.

### Is it ok to ask if my surgeon and anesthesiologist are qualiﬁed to look after my child?
Absolutely. Evidence of qualiﬁcations, training, and experience should be available, and your doctor will be able to show this at an appropriate time. Many doctors also take part in quality assurance programs. Some hospitals have a special accreditation for care of children and are subject to peer review to make sure standards are met and maintained.

### What can I as a parent do to help my child?
Being present to give information and comfort to your child are helpful although it can be stressful for you.


### Where can I get more information or help? 
Follow these useful links to up to date information and advice.

#### Rights of the child 
- EACH Charter
- Information about anesthesia for children, young people and families
- Information for children, carers and parents. Royal College of Anesthetists.
- What is a pediatric anesthesiologist? Healthchildren.org
- Useful information for those children with learning difficulties
- My Daycase Operation -- A Resource for Children with Learning Difficulty. Royal College of Anesthetists.
- Hospital Procedures. WidgitHealth
- Information about risks of anesthesia

#### Risks associated with anaesthesia. RCOA
- Risks associated with anaesthesia. Association of Anaesthetists UK.
- Joint professional guidance on the use of general anaesthesia in young children. APA, RCOA, AAGBI, CAI
- Hansen TG. Use of anaesthetics in young children: Consensus statement of the European Society of Anaesthesiology (ESA), the European Society for Paediatric Anaesthesiology (ESPA), the European Association of Cardiothoracic Anaesthesiology (EACTA) and the European Safe Tots Anaesthesia Research Initiative (EuroSTAR). Eur J Anaesthesiol. 2017 Jun;34(6):327-328. 

