## No Emergence Delirium (10Ns)

### Definition
Emergence delirium is part of an early negative postoperative behavior. It is an abnormal mental state following anesthesia and surgery and separate to pain.

### Importance
Emergence delirium is common following general anesthesia in young children. Effective recognition and treatment is essential to reduce self-inflicted injuries and improve satisfaction of parents and caregivers.

### Consequences
Emergence delirium may result in self-injury of the child and increase the healthcare requirements:
-   emergence delirium reduces parental and caregivers' satisfaction
-   short- and long-term psychological implications of emergence delirium are unclear
-   children with emergence delirium may have a higher risk of developing separation anxiety, apathy, and sleep and eating disorders

### Good practice points
-   be aware of risk factors and triggers
-   ensure appropriate information for child and parents is given in advance
-   effective local standardized protocols for prevention, recognition and treatment including non-drug treatment and involvement of parents in recovery process after anesthesia

### Key references
-   "This educational article defines Emergence Delirium and details the incidence, causes, risk factors and methods of measurement. Preventative strategies and treatment options are described clearly." Reduque LL, Verghese ST. Paediatric emergence delirium. Continuing Education in Anaesthesia Critical Care & Pain, Volume 13, Issue 2, April 2013, Pages 39--41, https://doi.org/10.1093/bjaceaccp/mks051
-   "This is a detailed single-author review of the state of the art regarding emergence delirium as of 2017." Mason KP. Paediatric emergence delirium: a comprehensive review and interpretation of the literature. Br J Anaesth. 2017 Mar 1;118(3):335-343. doi: 10.1093/bja/aew477
-   Line Gry Larsen, Marie Wegger, Sebastian Lé Greves, Liv Erngaard, Tom G Hansen. Emergence agitation in paediatric day case surgery: A randomised, single-blinded study comparing narcotrend and heart rate variability with standard monitoring. Eur J Anaesthesiol. 2022 Mar 1;39(3):261-268.

