## No Pain (10Ns)
It refers to the concept No Postoperative Discomfort

### Definition
Unpleasant sensory and emotional experience associated with actual or potential tissue damage or described in terms of such.

### Importance
A large number of children still experience significant pain in the perioperative period. Poor pain control remains a significant problem following hospital discharge.

### Consequences
Inadequate peri-operative pain control can lead to a variety of behavioral and somatic changes.

**These include:**
* altered behavior (emotional)
* subsequent altered pain perception
* prolonged hospital stays and increased re-admission rates
* chronic pain
* negative parental perception
* social consequences

### Good Practice Points
* regularly assess pain in all children to "make pain visible"
* chart pain as a vital sign
* ensure clear appropriate protocols to bring pain scores down and to maintain low pain scores
* reassess pain after analgesic interventions to ensure efficacy and to minimize side effects (titration)
* use multimodal analgesia and opioid-sparing techniques where possible and as appropriate
* ensure continuing analgesia at home

### Follow-Up/ Outcome
* audit pain assessments, high pain scores and pain at home and plan QI initiatives
* audit adverse effects, critical incidents and drug errors and make plans to reduce incidence

### Key references
* "These are the 2nd edition of the APAGBI evidence-based guidelines on pain management in children from 2012. They provide detailed reviews of pain assessment, non-pharmacological and pharmacological methods of pain management for all ages of children undergoing surgery or procedures." APAGBI. Good practice in postoperative and procedural pain management (2nd Edition). Paediatr Anaesth. 2012 Jul;22 Suppl 1:1-79. doi: 10.1111/j.1460-9592.2012.03838.x
* "This is the most comprehensive evidence-based resource on pain physiology, psychology, pharmacology, assessment and management currently available. The paediatric recommendations in Chapter 9 are excellent and highly recommended." Schug SA, Palmer GM, Scott DA, Halliwell R, Trinca J. Acute pain management: scientific evidence, fourth edition, 2015. Med J Aust. 2016 May 2;204(8):315-7. http://fpm.anzca.edu.au/documents/apmse4*2015*fina
* "These are the UK national procedural sedation guidelines from 2010. The full guidelines and supporting documentation are free to download. The principles described support safe practice but some regard the practice as somewhat conservative. An update is due in 2020." Sury M, Bullock I, Rabar S, Demott K; Guideline Development Group. Sedation in children and young people. Sedation for diagnostic and therapeutic procedures in children and young people. BMJ. 2010 Dec 16;341:c6819. https://www.nice.org.uk/guidance/cg11
* "This document summarises good practice guidance from ESPA to try to improve paediatric pain management across Europe." Vittinghoff M et al. Postoperative pain management in children: Guidance from the pain committee of the European Society for Paediatric Anaesthesiology (ESPA Pain Management Ladder Initiative). Paediatr Anaesth. 2018 Jun;28(6):493-506. doi: 10.1111/pan.13373. Epub 2018 Apr 10
* "These are very comprehensive evidence-based guidelines that give practical advice on how to recognise and assess pain in children. There are useful algorithms and posters to help introduce these ideas into your hospital." Royal College of Nursing. The recognition and assessment of acute pain in children. 2009. https://www.rcn.org.uk/professional-development/publications/pub-00354

