## Normonatremia (10Ns)

### Definition
Normal plasma sodium concentration within the age specific range.

### Importance
Plasma sodium is the major determinant of serum osmolality and therefore extracellular fluid volume. It is also a major determinant of neuronal excitability. Acute perioperative changes in plasma sodium concentrations are a leading cause of avoidable morbidity and mortality in children.

### Consequences
-   acute and severe hyponatremia may result in neurological damage and death (cerebral edema, seizures, transtentorial herniation)
-   rapid correction of hyponatremia may result in pontine myelinolysis.

### Prevention and treatment
-   consider the need for prolonged parenteral fluid administration
-   use balanced isotonic solutions
-   regular perioperative assessment sodium if continuous fluid therapy
-   avoid acute fluctuations of plasma sodium concentrations

### Key references
-   Sümpelmann R, Becke K, Brenner S, Breschan C, Eich C, Höhne C, Jöhr M, Kretz FJ, Marx G, Pape L, Schreiber M, Strauss J, Weiss M. Perioperative intravenous fluid therapy in children: guidelines from the Association of the Scientific Medical Societies in Germany. Paediatr Anaesth. 2017 Jan;27(1):10-18.
-   NICE guidelines: Intravenous fluid therapy in children and young people in hospital
-   The Inquiry into hyponatremia-related deaths. Last accessed 5/2019
-   Lönnqvist PA. Inappropriate perioperative fluid management in children: time for a solution?! Paediatr Anaesth. 2007; 17:203-5.

