## Normovolemia (10Ns)

### Definition
Maintenance of expected circulating blood volume and body fluid homeostasis of the patient (age dependent).

### Importance
Maintenance of physiological body fluid homeostasis is important for normal organ function. Deviations from this equilibrium (hypo- and hypervolemia) are commonly encountered in the peri-operative period.

### Consequences

#### Hypovolemia
- results in hypoperfusion and tissue hypoxia
- hypovolemia is the leading cause of perioperative cardiac arrests (POCA) in children

#### Hypervolemia
- dilutional coagulopathy
- tissue edema

### Prevention and treatment
- preoperative clinical assessment (capillary refill time, urinary output) and correct preoperative disturbances if required
- consider using other monitors which may include: invasive pressure monitoring, SvO2, repeated, periodical arterial blood gas analysis (acid base state) and non-invasive cardiac output monitors

#### Hypovolemia
- avoid prolonged fasting times which can lead to hypovolemia
- correct / minimize pre-operative deficits
- sufficient IV access (size and number)
- maintenance fluids
- blood and coagulation management

#### Hypervolemia
- close monitoring and control of fluid administration
- correction of intraoperative coagulopathy

### Key references
- Sümpelmann R, Becke K, Brenner S, Breschan C, Eich C, Höhne C, Jöhr M, Kretz FJ, Marx G, Pape L, Schreiber M, Strauss J, Weiss M. Perioperative intravenous fluid therapy in children: guidelines from the Association of the Scientific Medical Societies in Germany. Paediatr Anaesth. 2017 Jan;27(1):10-18. doi: 10.1111/pan.13007.

