## The Safetots Mission and Story

### Story
**Laboratory research over the past 2 decades has raised concerns** about the effects of anesthesia and surgery in the developing brain.

**There is a controversy if neuromorbidity** may result from the potentially toxic effects of anesthetic drugs on the central nervous system or may arise from an inappropriate conduct of anesthesia and from surgery.

**The SmartTots public-private partnership** focuses on studying the harmful effects of anesthetics on the developing brain.

**The Safetots.org initiative was established to emphasize the role of the conduct of anesthesia** to prevent harm in the perioperative period and to promote safe and high quality clinical care. This initiative considers that the quality of anesthesia management and other well-known risk factors of perioperative care have a far more important impact on outcomes following anesthesia and surgery.

**The Safetots.org initiative aims to bring together healthcare providers** in the field of pediatric perioperative care.

